apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: react-map
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: react-map
    spec:
      containers:
        - name: react-map
          image: 744004065806.dkr.ecr.ap-southeast-1.amazonaws.com/dev-bidding-service:react-map
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

---
apiVersion: v1
kind: Service
metadata:
  name: react-map
  labels:
    app: react-map
spec:
  selector:
    app: react-map
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: react-map
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  rules:
    - host: map.danghung.xyz
      http:
        paths:
          - path: /
            backend:
              serviceName: react-map
              servicePort: 80
